services:
  db:
    image: mongo:7
    container_name: raizes_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: raizes_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PORT: "3000"
      DATABASE_URL: "mongodb://db:27017/raizes_nordeste"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRES_IN: "1h"
      NODE_ENV: "production"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "node --experimental-transform-types --import=./scripts/loader.ts scripts/seed.ts && npx tsx src/server.ts"

volumes:
  mongodata:
